name: ci

on:
  schedule:
    - cron: "0 10 * * 0" # Every Sunday at 10am
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: spark
            version: "3.0.2"
            latest: true
            description: Apache Spark with Python updated to 3.7.
            build-args: ""
          - image: zeppelin
            version: "0.9.0"
            latest: true
            description: Apache Zeppelin bundled with Spark 3.0.2 and Hadoop 3.2.
            build-args: |
              SPARK_VERSION=3.0.2
              HADOOP_VERSION=3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=${{ matrix.latest }}
          labels: |
            org.opencontainers.image.title=sketchbench-${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.description }}
            org.opencontainers.image.vendor=SketchBench
          images: |
            sketchbench/sketchbench-${{ matrix.image }}
            ghcr.io/SketchBench/sketchbench-${{ matrix.image }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ matrix.version }}
            type=sha
            type=edge
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./images/${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: ${{ matrix.build-args }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=sketchbench/sketchbench-${{ matrix.image }}:main
          cache-to: type=inline
      - name: Inspect image
        if: github.event_name != 'pull_request'
        run: |
          docker pull sketchbench/sketchbench-${{ matrix.image }}:${{ matrix.version }}
          docker image inspect sketchbench/sketchbench-${{ matrix.image }}:${{ matrix.version }}
      - name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect sketchbench/sketchbench-${{ matrix.image }}:${{ matrix.version }}
      - name: Update Docker Hub repo description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: sketchbench/sketchbench-${{ matrix.image }}
          short-description: ${{ matrix.description }}
          readme-filepath: ./images/${{ matrix.image }}/README.md
